### ISSUE TITLE
Trouble with spacing

### ISSUE THREAD

**Issue by vanlong441** [zacbarton/gnome-shell-extension-bolt#1]
Below are some pictures I took. Notice the difference between the first two, with Bolt disabled, and the last ones, with Bold enabled. With Bolt enabled, the spacing between texts are very little. I can't find any value of padding/spacing in a Shell theme that affects this kind of spacing. Therefore, I guess the solution might come from some values in files in /usr/share/gnome-shell/js/ui

http://imgur.com/a/8GYt1#0

Hope that helped. Thank you for the extension and keep up the good work.

**Comment by zacbarton** [comment]
The screen-shots don't show Bolt running but a different launcher/menu. Was this issue meant for a different project?

**Comment by vanlong441** [comment]
ah, that is Axemenu https://extensions.gnome.org/extension/327/axe-menu/. It makes no difference with or without that menu. The spacing issue was so clear with that extension so I included it in the screenshots. Here is the screenshot without Axemenu 

http://imgur.com/a/8GYt1#4

**Comment by 0rAX0** [comment]
@zacbarton I think he's right. Bolt is killing other extensions in themes that don't style them. I haven't noticed it before because I was only testing with eOS. Which it has fixes for extensions.

Steps to reproduce:
- Use the default theme(or any theme that doesn't style 3rd party extensions).
- Make sure Bolt is disabled. And restart the shell Alt+f2 > r.
- Enable the Weather extension. It should look fine.
- Now enable bolt.
- The Weather extension will look bad.

Even if you disable Bolt after that and enable another menu, the effect will remain until Alt+F2 > r.

I think that's because all of those /_killing user themes_/ styles with !important. :)
